spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
############# Cloudinary ################
cloud.name=${CLOUDINARY_CLOUD_NAME:mhussainshah1}
cloud.secret=${CLOUDINARY_API_SECRET:TumEYd__zLe37QbN-J_UBRqQ3Rk}
cloud.key=${CLOUDINARY_API_KEY:195135636893328}
run.dataloader=false
################ Open Weather API ###################
weather.url=api.openweathermap.org/data/2.5/weather
weather.apikey=75b5469d29c87461d0a6e2771208d3b5
#####To avoid double validation#######
spring.jpa.properties.javax.persistence.validation.mode=none